### PR TITLE
fixed icons in cobench report

### PR DESCRIPTION
**Pull request by Graur**
What's done: 

- fixed icon representation in retpor

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 I'm not sure about this change, since I can't build the report. But looks like this change can help to make pictures of profiles in report works

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.47`

**Comment by yegor256** [comment]
@Graur thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.47`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.47`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.47`

**Pull request merged**
